config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies, shallow: true do
    resources :reviews, only: [ :create, :show, :destroy, :update ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  validates :content, presence: true
  validates :rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :destroy, :edit, :update]

  def index
    @movies = Movie.all
  end

  def show
    @review = Review.new
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if Movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :year)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :destroy, :update]
  before_action :find_movie, only: [:create]

  def show
  end

  def destroy
    @review.destroy
    redirect_to movie_path(@review.movie)
  end

  def create
    @review = @movie.reviews.new(review_params)
    if @review.save
      redirect_to movie_path(@movie)
    else
      render 'movies/show'
    end
  end

  def update
    if Review.update(review_params)
      redirect_to movie_path(@review.movie)
    else
      render :show
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def find_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/movies/edit.html.erb
<%= simple_form_for @movie do |f| %>
  <%= f.input :name %>
  <%= f.input :synopsis, as: :text %>
  <%= f.input :year, as: :integer %>
  <%= f.button :submit %>
<% end %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
<li><%= link_to "#{movie.name}", movie_path(movie) %>,
  [<%= link_to "Edit this movie", edit_movie_path(movie) %>]
</li>

<% end %>
<br>
<%= link_to "Add a movie", new_movie_path %>

app/views/movies/new.html.erb
<%= simple_form_for @movie do |f| %>
  <%= f.input :name %>
  <%= f.input :synopsis, as: :text %>
  <%= f.input :year, as: :integer %>
  <%= f.button :submit %>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.name %> </h1>
<%= link_to "Delete this movie", movie_path(@movie), method: :delete  %>


<h3>Add a review</h3>

<%= simple_form_for [@movie, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :integer %>
  <%= f.button :submit %>
<% end %>

<% @movie.reviews.each do |review| %>
  <% if review.persisted? %>
    <p><%= review.content %> - <%= review.rating %>, ><%= link_to "More about", review_path(review) %></p>
  <% end %>
<% end %>

app/views/pages/home.html.erb
<h1>RORO CINE</h1>

<%= link_to "index des films", movies_path %>

app/views/reviews/show.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Delete this review", review_path(@review), method: :delete  %>